version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  pre_build:
    commands:
      - aws s3 cp s3://elasticbeanstalk-eu-north-1-117572039742/.ebextensions/ .ebextensions/ --recursive
      - aws s3 cp s3://elasticbeanstalk-eu-north-1-117572039742/.platform/ .platform/ --recursive
  build:
    commands:
      - dotnet publish -c Release -o output
      - cp -r .ebextensions output/
      - cp -r .platform output/
  post_build:
    commands:
      - cd output
      - zip -r ../build.zip .
artifacts:
  files:
    - build.zip