version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  pre_build:
    commands:
      - aws s3 cp s3://elasticbeanstalk-eu-north-1-117572039742/.ebextensions/ .ebextensions/ --recursive
      - aws s3 cp s3://elasticbeanstalk-eu-north-1-117572039742/.platform/ .platform/ --recursive
  build:
    commands:
      - dotnet restore
      - dotnet publish -c Release -o published
      - mkdir -p published/.ebextensions
      - cp -r .ebextensions/* published/.ebextensions/
      - mkdir -p published/.platform
      - cp -r .platform/* published/.platform/
artifacts:
  files:
    - '**/*'
  base-directory: 'published'
